[tool.poetry]
name = "sqa-http"
version = "0.1.0"
description = ""
authors = ["Hirofumi Tsuruta"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
sqaod = "^1.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
